#
# Copyright (C) Patrik Jonell and contributors 2021.
# Licensed under the MIT license. See LICENSE.txt file in the project root for details.
#

version: '3'
services:
  webmushra:
    image: rubenjanss/hemvip_confusion:latest
    ports:
      - "8000:80"
    command: /start-reload.sh
    depends_on:
      - db
    environment:
      MONGO_USERNAME: confusion_user
      MONGO_PASSWORD: rwqetsrpyfig8
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      -configdb: /data/configdb
      -db: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: confusion_user
      MONGO_INITDB_ROOT_PASSWORD: rwqetsrpyfig8


volumes:
-db
-configdb