version: '3.7'
name: hemvip

services:
  webmushra:
    image: rubenjanss/hemvip_confusion:latest
    environment:
      MONGO_USERNAME: confusion_user
      MONGO_PASSWORD: rwqetsrpyfig8
    depends_on:
      - db
    command: /start-reload.sh
    restart: unless-stopped
    networks:
      - hemvip
      - caddy
    labels:
      caddy: http://hemvip.hri.ilabt.imec.be
      caddy.reverse_proxy: '{{upstreams 80}}'

  db:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: confusion_user
      MONGO_INITDB_ROOT_PASSWORD: rwqetsrpyfig8
    volumes:
      - db_config:/data/configdb
      - db_data:/data/db
    restart: unless-stopped
    networks:
      - hemvip
    # ports:
    #   - "27017:27017"


volumes:
  db_config:
  db_data:

networks:
  hemvip:
  caddy:
    external: true